<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PhimSeeder extends Seeder
{
    public function run()
    {
        DB::table('phim')->insert(values: [
            [
                'M_id' => 'F001',
                'tenPhim' => 'Vong Nhi',
                'thoiLuong' => 120,
                'moTa' => 'Vong nhi là một bộ phim điện ảnh Việt Nam thuộc thể loại tâm lý – siêu nhiên – kinh dị – chính kịch ',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://ss-images.saostar.vn/w1200/pc/1674140241319/saostar-mph8vmm41fqk7osk.jpg',
                'Trailer' => "https://www.youtube.com/embed/q6n589lkjE4",
                'imgBanner' => 'https://cdn.galaxycine.vn/media/2023/1/30/vong-nhi-1_1675048542706.jpg',
            ],
            [
                'M_id' => 'F002',
                'tenPhim' => 'Quỷ nhập tràng',
                'thoiLuong' => 151,
                'moTa' => 'Phim lấy cảm hứng từ câu chuyện có thật và “truyền thuyết kinh dị nhất về người chết sống lại”',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://cdn.mobilecity.vn/mobilecity-vn/images/2025/03/review-phim-quy-nhap-trang-anh-dai-dien.jpg.webp',
                'Trailer' => 'https://www.youtube.com/embed/QTH8KnbWJkc',
                'imgBanner' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtEg-vme2Q7AI0KwlrcJPWdk1rFd9ht0rcWA&s',
            ],
            [
                'M_id' => 'F003',
                'tenPhim' => 'EMMA VÀ VƯƠNG QUỐC TÍ HON',
                'thoiLuong' => 106,
                'moTa' => 'Phim xoay quanh cô nàng bé nhỏ Emma được động vật nuôi lớn, thế nhưng luôn có sự tò mò về nguồn gốc của mình. ',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://cdn.galaxycine.vn/media/2025/2/20/emma-750_1740043373928.jpg',
                'Trailer' => 'https://www.youtube.com/embed/kraUpgr_IE4',
                'imgBanner' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzl9i342olVlcDHMrmMfAFsNaOWbuMB48o4w&s',
            ],
            [
                'M_id' => 'F004',
                'tenPhim' => 'Lạc trôi',
                'thoiLuong' => 85,
                'moTa' => 'Lạc trôi là một bộ phim điện ảnh hoạt hình thuộc thể loại phiêu lưu – kỳ ảo – chính kịch ',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://touchcinema.com/storage/slider-app/2048x682-1-1740711284334.jpg',
                'Trailer' => ' https://www.youtube.com/embed/vob8AGZM4Wc',
                'imgBanner' => 'https://upload.wikimedia.org/wikipedia/vi/9/96/FLOW_%E2%80%93_Vietnam_poster.jpg',
            ],
            [
                'M_id' => 'F005',
                'tenPhim' => 'Nụ Hôn Bạc Tỷ',
                'thoiLuong' => 100,
                'moTa' => 'Nụ Hôn Bạc Tỷ, nơi câu chuyện hài hước về tình chị em "chí choé nhưng yêu thương hết lòng" sẽ khiến bạn cười ngất và rưng rưng cảm động. ',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://image.anninhthudo.vn/1200x630/Uploaded/2025/reyxqmdffr/2024_11_28/nu-hon-bac-ty-teaser-poster-kc-29012025-1-4937.jpg',
                'Trailer' => ' https://www.youtube.com/embed/dIPLDSQA3Rg',
                'imgBanner' => 'https://cdn.galaxycine.vn/media/2024/12/11/nu-hon-bac-t-500_1733902817624.jpg',
            ],
            [
                'M_id' => 'F006',
                'tenPhim' => 'Anh Không Đau',
                'thoiLuong' => 110,
                'moTa' => 'Novocain là một bộ phim hài hành động của Mỹ năm 2025 do Dan Berk và Robert Olsen đạo diễn và Lars Jacobson viết kịch bản. ',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://chieuphimquocgia.com.vn/_next/image?url=http%3A%2F%2Fapiv2.chieuphimquocgia.com.vn%2FContent%2FImages%2FBanner%2F0018422.jpg&w=3840&q=75',
                'Trailer' => 'https://www.youtube.com/embed/FNBbFHgPzyY',
                'imgBanner' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-tPEVd_7LVX152HQFV1yy3idbLdNSFVh37w&s',
            ],
            ['M_id' => 'F011',
                'tenPhim' => 'Thần dược',
                'thoiLuong' => 140,
                'moTa' => 'Thần dược là một bộ phim điện ảnh thuộc thể loại kinh dị – châm biếm – tâm lý – giật gân ra mắt vào năm 2024 do Coralie Fargeat viết kịch bản, đạo diễn, đồng biên tập và đồng sản xuất.',
                'trangThai' => 'Đã chiếu',
                'Poster' => 'https://touchcinema.com/storage/slider-app/1440-x-600.png',
                'Trailer' => 'https://www.youtube.com/embed/LNlrGhBpYjc',
                'imgBanner' => 'https://khenphim.com/wp-content/uploads/2024/10/The-Substance-pic1-poster_KP-scaled.webp',
            ],
            [
                'M_id' => 'F008',
                'tenPhim' => 'Bí Mật Không Thể Nói',
                'thoiLuong' => 125,
                'moTa' => 'Bí Mật Không Thể Nói 2025 được chuyển thể từ siêu phẩm lãng mạn cùng tên của Châu Kiệt Luân',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://cdn.galaxycine.vn/media/2025/1/24/bi-mat-khong-the-noi-750_1737689641139.jpg',
                'Trailer' => 'https://www.youtube.com/embed/Z0b8YERgcB8',
                'imgBanner' => 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/p/o/poster_bi_mat_khong_the_noi_10.jpg',
            ],
            [
                'M_id' => 'F009',
                'tenPhim' => 'Nhà Gia Tiên',
                'thoiLuong' => 117,
                'moTa' => 'Người vui vẻ, kẻ trở nên lạ lùng khi thấy điều kì lạ xảy ra trước mắt. Chuyện gì đang xảy ra?',
                'trangThai' => 'Đã chiếu',
                'Poster' => 'https://thanhnienviet.mediacdn.vn/thumb_w/730/original/677402384f700_1.jpg',
                'Trailer' => 'https://www.youtube.com/embed/IKa3KQNyEnw',
                'imgBanner' => 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/3/image/c5f0a1eff4c394a251036189ccddaacd/p/a/payoff_poster_ngt_master_sneak-2_1_.jpg',
            ],
            [
                'M_id' => 'F010',
                'tenPhim' => 'Sát thủ vô cùng cực',
                'thoiLuong' => 110,
                'moTa' => 'Câu chuyện tiếp nối về cuộc đời làm hoạ sĩ webtoon Jun, người nổi tiếng trong thời gian ngắn với tư cách là tác giả của webtoon Đặc vụ ám sát Jun',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://cdn.mobilecity.vn/mobilecity-vn/images/2025/03/review-phim-sat-thu-vo-cung-cuc-hai-anh-dai-dien.jpg.webp',
                'Trailer' => 'https://www.youtube.com/embed/v81sGxKvBfk',
                'imgBanner' => 'https://static2.vieon.vn/vieplay-image/poster_v4/2023/03/01/a4kjtyow_660x946-satthuvocungcuc_360_534.jpeg',
            ],
            [
                'M_id' => 'F012',
                'tenPhim' => 'NGHỀ SIÊU KHÓ NÓI',
                'thoiLuong' => 102,
                'moTa' => 'Dan-bi vốn mơ ước trở thành một tác giả truyện thiếu nhi, nhưng trớ trêu thay, cô lại khởi đầu sự nghiệp tại Đội Bảo vệ Thanh thiếu niên ',
                'trangThai' => 'Sắp chiếu',
                'Poster' => 'https://i.ytimg.com/vi/25NyBoZOoWc/maxresdefault.jpg',
                'Trailer' => 'https://www.youtube.com/embed/25NyBoZOoWc',
                'imgBanner' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRBvwQ403j4nqZVsLUGfuQjy7wkiqu5RJImQ&s',
            ],
            [
                'M_id' => 'F013',
                'tenPhim' => 'Gặp lại chị bầu',
                'thoiLuong' => 114,
                'moTa' => 'Gặp lại chị bầu là một bộ phim điện ảnh Việt Nam thuộc thể loại hài lãng mạn – chính kịch ra mắt vào năm 2024 do Đoàn Nhất Trung làm đạo diễn.',
                'trangThai' => 'Đã chiếu',
                'Poster' => 'https://starlight.vn/Areas/Admin/Content/Fileuploads/images/POSTER/gap%20lai%20chi%20bau.jpg',
                'Trailer' => 'https://www.youtube.com/embed/qWN2gpls2R0',
                'imgBanner' => 'https://boxofficevietnam.com/wp-content/uploads/2024/01/65672ba7d2a73642668289.jpeg',
            ],
            [
                'M_id' => 'F014',
                'tenPhim' => 'Captain America: Thế giới mới',
                'thoiLuong' => 120,
                'moTa' => 'Nhiệm vụ: Vén màn sự thật trước khi cả thế giới đổ máu. Captain America: Thế Giới Mới từ Marvel Studios ',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://media.lottecinemavn.com/Media/MovieFile/MovieImg/202501/11610_105_100001.jpg',
                'Trailer' => 'https://www.youtube.com/embed/45YkmSVLBrI',
                'imgBanner' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrR1k8C92vDCDfxbc1m-VgFY2tF90cxD2sXw&s',
            ],
            [
                'M_id' => 'F015',
                'tenPhim' => 'BUỔI HẸN HÒ KINH HOÀNG',
                'thoiLuong' => 95,
                'moTa' => 'Buổi hẹn hò đầu tiên sau nhiều năm của Violet nhanh chóng trở thành ác mộng khi cô nhận được những tin nhắn ẩn danh kỳ lạ. ',
                'trangThai' => 'Sắp chiếu',
                'Poster' => 'https://i.ytimg.com/vi/cQ1eYm_XIcA/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBf3KJ-Opqn-AVWEmzEdti-fhPWcg',
                'Trailer' => 'https://www.youtube.com/embed/cQ1eYm_XIcA',
                'imgBanner' => 'https://cdn.moveek.com/storage/media/cache/tall/679344e4e9aa3017021933.jpg',
            ],
            [
                'M_id' => 'F016',
                'tenPhim' => 'Đố Anh Còng Được Tôi ',
                'thoiLuong' => 95,
                'moTa' => 'Đố Anh Còng Được Tôi" (I, Executioner) là một trong những bộ phim chiếu rạp hành động Hàn Quốc hay ',
                'trangThai' => 'Đã chiếu',
                'Poster' => 'https://media.lottecinemavn.com/Media/MovieFile/MovieImg/202409/11560_105_100001.jpg',
                'Trailer' => 'https://www.youtube.com/embed/JgUWVooKSrA',
                'imgBanner' => 'https://www.elle.vn/wp-content/uploads/2024/08/29/605369/hwang-jung-min-trong-poster-do-anh-cong-duoc-toi.jpg',
            ],
            [
                'M_id' => 'F017',
                'tenPhim' => 'Hai muối',
                'thoiLuong' => 101,
                'moTa' => 'Muối – một cô gái mất mẹ từ khi vừa lọt lòng và lớn lên trong tình yêu thương của cha tại vùng đất xã đảo Thiềng Liềng. ',
                'trangThai' => 'Đã chiếu',
                'Poster' => 'https://2saigon.vn/wp-content/uploads/2024/08/HAI-MUOI-PAYOFF-POSTER-KTHUOC-FACEBOOK.jpg',
                'Trailer' => 'https://www.youtube.com/embed/MjxPoqCvvVs',
                'imgBanner' => 'https://2saigon.vn/wp-content/uploads/2024/08/HAI-MUOI-PAYOFF-POSTER-KTHUOC-FACEBOOK-.jpg',
            ],
            [
                'M_id' => 'F018',
                'tenPhim' => 'NÀNG BẠCH TUYẾT',
                'thoiLuong' => 108,
                'moTa' => 'Phiên bản chuyển thể người đóng của bộ phim hoạt hình Bạch Tuyết & Bảy chú lùn của Disney năm 1937.',
                'trangThai' => 'Sắp chiếu',
                'Poster' => 'https://i.ytimg.com/vi/cJh3IhW7wjo/maxresdefault.jpg',
                'Trailer' => 'https://www.youtube.com/embed/cJh3IhW7wjo',
                'imgBanner' => 'https://starlight.vn/Areas/Admin/Content/Fileuploads/images/Poster2024/snow-white.jpg',
            ],
            [
                'M_id' => 'F019',
                'tenPhim' => 'Cưới Ma: Hiến Mẹ Cho Quỷ ',
                'thoiLuong' => 104,
                'moTa' => 'Cưới ma: Hiến mẹ cho quỷ (Pengantin Iblis) là một bộ phim chiếu rạp kinh dị Indonesia của đạo diễn Azhar Kinoi Lubis',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/3/image/1800x/71252117777b696995f01934522c402d/6/4/640x396-cuoima.jpg',
                'Trailer' => 'https://www.youtube.com/embed/ZkW-Zb-EICA',
                'imgBanner' => 'https://i.ytimg.com/vi/Dg9YzHxEkWU/oardefault.jpg?sqp=-oaymwEiCJwEENAFSFqQAgHyq4qpAxEIARUAAAAAJQAAyEI9AICiQw==&rs=AOn4CLDEpn_Om4vWIs2AdRedj3AnPJMCHA',
            ],
            [
                'M_id' => 'F020',
                'tenPhim' => 'PHIM ĐIỆN ẢNH DORAEMON: NOBITA VÀ CUỘC PHIÊU LƯU VÀO THẾ GIỚI TRONG TRANH',
                'thoiLuong' => 140,
                'moTa' => 'Thông qua món bảo bối mới của Doraemon, cả nhóm bạn bước thế giới trong một bức tranh nổi tiếng và bắt gặp cô bạn bí ẩn tên Claire. ',
                'trangThai' => 'Sắp chiếu',
                'Poster' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWzicdqpKvxTUoBMb0En_O6sM6L52Tlk6klw&s',
                'Trailer' => 'https://www.youtube.com/embed/Bz0zCdNBj1Q',
                'imgBanner' => 'https://cdn.galaxycine.vn/media/2025/3/11/doraemon-the-movie-nobitas-art-world-tales-2_1741663608345.jpg',
            ],
        ]);
    }
}
