<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PhimSeeder extends Seeder
{
    public function run()
    {
        DB::table('phim')->insert(values: [
            [
                'M_id' => 'F001',
                'tenPhim' => 'Vong Nhi',
                'thoiLuong' => 120,
                'moTa' => 'Vong nhi là một bộ phim điện ảnh Việt Nam thuộc thể loại tâm lý – siêu nhiên – kinh dị – chính kịch ',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://ss-images.saostar.vn/w1200/pc/1674140241319/saostar-mph8vmm41fqk7osk.jpg',
                'Trailer' => "https://www.youtube.com/embed/q6n589lkjE4",
                'imgBanner' => 'https://cdn.galaxycine.vn/media/2023/1/30/vong-nhi-1_1675048542706.jpg',
            ],
            [
                'M_id' => 'F002',
                'tenPhim' => 'Quỷ nhập tràng',
                'thoiLuong' => 151,
                'moTa' => 'Phim lấy cảm hứng từ câu chuyện có thật và “truyền thuyết kinh dị nhất về người chết sống lại” - Ở một ngôi làng vùng cao, cặp vợ chồng Quang và Như sống bằng nghề mai táng. Cuộc sống yên bình của họ bị xáo trộn khi phát hiện một cỗ quan tài vô chủ trên mảnh đất nhà mình.',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://cdn.mobilecity.vn/mobilecity-vn/images/2025/03/review-phim-quy-nhap-trang-anh-dai-dien.jpg.webp',
                'Trailer' => 'https://www.youtube.com/embed/QTH8KnbWJkc',
                'imgBanner' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtEg-vme2Q7AI0KwlrcJPWdk1rFd9ht0rcWA&s',
            ],
            [
                'M_id' => 'F003',
                'tenPhim' => 'EMMA VÀ VƯƠNG QUỐC TÍ HON',
                'thoiLuong' => 106,
                'moTa' => 'Phim xoay quanh cô nàng bé nhỏ Emma được động vật nuôi lớn, thế nhưng luôn có sự tò mò về nguồn gốc của mình. Một ngày nọ, Emma quyết định lên đường khám phá vùng đất con người, tìm lại tổ tiên của mình, nhưng rồi sự thật của nơi đây đẩy cô và các bạn vào những cuộc phiêu lưu mạo hiểm, hồi hộp.',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://cdn.galaxycine.vn/media/2025/2/20/emma-750_1740043373928.jpg',
                'Trailer' => 'https://www.youtube.com/embed/kraUpgr_IE4',
                'imgBanner' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzl9i342olVlcDHMrmMfAFsNaOWbuMB48o4w&s',
            ],
            [
                'M_id' => 'F004',
                'tenPhim' => 'Lạc trôi',
                'thoiLuong' => 85,
                'moTa' => 'Lạc trôi là một bộ phim điện ảnh hoạt hình thuộc thể loại phiêu lưu – kỳ ảo – chính kịch ra mắt vào năm 2024 do Gints Zilbalodis làm đạo diễn, viết kịch bản và đồng sản xuất, đồng thời còn đảm nhận cả vai trò quay phim, biên tập và soạn nhạc phim.',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://touchcinema.com/storage/slider-app/2048x682-1-1740711284334.jpg',
                'Trailer' => ' https://www.youtube.com/embed/vob8AGZM4Wc',
                'imgBanner' => 'https://upload.wikimedia.org/wikipedia/vi/9/96/FLOW_%E2%80%93_Vietnam_poster.jpg',
            ],
            [
                'M_id' => 'F005',
                'tenPhim' => 'Nụ Hôn Bạc Tỷ',
                'thoiLuong' => 100,
                'moTa' => 'Nụ Hôn Bạc Tỷ, nơi câu chuyện hài hước về tình chị em "chí choé nhưng yêu thương hết lòng" sẽ khiến bạn cười ngất và rưng rưng cảm động. Những pha "quăng miếng" siêu duyên dáng, tình tiết bất ngờ, và một nụ hôn đầy định mệnh – tất cả hứa hẹn một trải nghiệm Tết không thể bỏ qua!',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://image.anninhthudo.vn/1200x630/Uploaded/2025/reyxqmdffr/2024_11_28/nu-hon-bac-ty-teaser-poster-kc-29012025-1-4937.jpg',
                'Trailer' => ' https://www.youtube.com/embed/dIPLDSQA3Rg',
                'imgBanner' => 'https://cdn.galaxycine.vn/media/2024/12/11/nu-hon-bac-t-500_1733902817624.jpg',
            ],
            [
                'M_id' => 'F006',
                'tenPhim' => 'Anh Không Đau',
                'thoiLuong' => 110,
                'moTa' => 'Novocain là một bộ phim hài hành động của Mỹ năm 2025 do Dan Berk và Robert Olsen đạo diễn và Lars Jacobson viết kịch bản. Phim có sự tham gia của Jack Quaid, Amber Midthunder, Ray Nicholson, Betty Gabriel và Jacob Batalon.',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://chieuphimquocgia.com.vn/_next/image?url=http%3A%2F%2Fapiv2.chieuphimquocgia.com.vn%2FContent%2FImages%2FBanner%2F0018422.jpg&w=3840&q=75',
                'Trailer' => 'https://www.youtube.com/embed/FNBbFHgPzyY',
                'imgBanner' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-tPEVd_7LVX152HQFV1yy3idbLdNSFVh37w&s',
            ],
            ['M_id' => 'F011',
                'tenPhim' => 'Thần dược',
                'thoiLuong' => 140,
                'moTa' => 'Thần dược là một bộ phim điện ảnh thuộc thể loại kinh dị – châm biếm – tâm lý – giật gân ra mắt vào năm 2024 do Coralie Fargeat viết kịch bản, đạo diễn, đồng biên tập và đồng sản xuất.',
                'trangThai' => 'Đã chiếu',
                'Poster' => 'https://touchcinema.com/storage/slider-app/1440-x-600.png',
                'Trailer' => 'https://www.youtube.com/embed/LNlrGhBpYjc',
                'imgBanner' => 'https://khenphim.com/wp-content/uploads/2024/10/The-Substance-pic1-poster_KP-scaled.webp',
            ],
            [
                'M_id' => 'F008',
                'tenPhim' => 'Bí Mật Không Thể Nói',
                'thoiLuong' => 125,
                'moTa' => 'Bí Mật Không Thể Nói 2025 được chuyển thể từ siêu phẩm lãng mạn cùng tên của Châu Kiệt Luân',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://cdn.galaxycine.vn/media/2025/1/24/bi-mat-khong-the-noi-750_1737689641139.jpg',
                'Trailer' => 'https://www.youtube.com/embed/Z0b8YERgcB8',
                'imgBanner' => 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/p/o/poster_bi_mat_khong_the_noi_10.jpg',
            ],
            [
                'M_id' => 'F009',
                'tenPhim' => 'Nhà Gia Tiên',
                'thoiLuong' => 117,
                'moTa' => 'Người vui vẻ, kẻ trở nên lạ lùng khi thấy điều kì lạ xảy ra trước mắt. Chuyện gì đang xảy ra?',
                'trangThai' => 'Đã chiếu',
                'Poster' => 'https://thanhnienviet.mediacdn.vn/thumb_w/730/original/677402384f700_1.jpg',
                'Trailer' => 'https://www.youtube.com/embed/IKa3KQNyEnw',
                'imgBanner' => 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/3/image/c5f0a1eff4c394a251036189ccddaacd/p/a/payoff_poster_ngt_master_sneak-2_1_.jpg',
            ],
            [
                'M_id' => 'F010',
                'tenPhim' => 'Sát thủ vô cùng cực',
                'thoiLuong' => 110,
                'moTa' => 'Câu chuyện tiếp nối về cuộc đời làm hoạ sĩ webtoon Jun, người nổi tiếng trong thời gian ngắn với tư cách là tác giả của webtoon Đặc vụ ám sát Jun, nhanh chóng mang danh là "nhà văn thiếu não" sau khi Phần 2 bị chỉ trích thảm hại, nhưng mọi thứ thay đổi khi một cuộc tấn công khủng bố ngoài đời thực giống hệt với phần 2 anh vừa xuất bản, khiến Jun bị NIS buộc tội sai là kẻ chủ mưu đằng sau tội ác.',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://cdn.mobilecity.vn/mobilecity-vn/images/2025/03/review-phim-sat-thu-vo-cung-cuc-hai-anh-dai-dien.jpg.webp',
                'Trailer' => 'https://www.youtube.com/embed/v81sGxKvBfk',
                'imgBanner' => 'https://static2.vieon.vn/vieplay-image/poster_v4/2023/03/01/a4kjtyow_660x946-satthuvocungcuc_360_534.jpeg',
            ],
            [
                'M_id' => 'F012',
                'tenPhim' => 'NGHỀ SIÊU KHÓ NÓI',
                'thoiLuong' => 102,
                'moTa' => 'Dan-bi vốn mơ ước trở thành một tác giả truyện thiếu nhi, nhưng trớ trêu thay, cô lại khởi đầu sự nghiệp tại Đội Bảo vệ Thanh thiếu niên, nơi chuyên kiểm duyệt nội dung khiêu dâm bất hợp pháp. Một ngày nọ, Dan-bi vô tình gây ra tai nạn và phải bồi thường một khoản tiền khổng lồ cho CEO Hwang – ông trùm trong ngành văn học mạng 18+. Từ đây, cô buộc phải ký thỏa thuận viết truyện người lớn để trả nợ. Vốn chưa từng viết truyện người lớn, Dan-bi gặp đủ tình huống dở khóc dở cười. Nhưng nhờ sự cổ vũ của đồng nghiệp Jung-seok - người đang vật lộn với chứng khó “lên”, và nhờ vốn sống phong phú từ hội bạn thân mê buôn chuyện giường chiếu, cô bỗng phát hiện ra tài năng sáng tác thiên phú mà chính mình cũng không ngờ tới…',
                'trangThai' => 'Sắp chiếu',
                'Poster' => 'https://i.ytimg.com/vi/25NyBoZOoWc/maxresdefault.jpg',
                'Trailer' => 'https://www.youtube.com/embed/25NyBoZOoWc',
                'imgBanner' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRBvwQ403j4nqZVsLUGfuQjy7wkiqu5RJImQ&s',
            ],
            [
                'M_id' => 'F013',
                'tenPhim' => 'Gặp lại chị bầu',
                'thoiLuong' => 114,
                'moTa' => 'Gặp lại chị bầu là một bộ phim điện ảnh Việt Nam thuộc thể loại hài lãng mạn – chính kịch ra mắt vào năm 2024 do Đoàn Nhất Trung làm đạo diễn. Tác phẩm có sự tham gia diễn xuất của các diễn viên gồm Diệu Nhi, Anh Tú Atus, Lê Giang, Vũ Quốc Khánh, Ngọc Phước',
                'trangThai' => 'Đã chiếu',
                'Poster' => 'https://starlight.vn/Areas/Admin/Content/Fileuploads/images/POSTER/gap%20lai%20chi%20bau.jpg',
                'Trailer' => 'https://www.youtube.com/embed/qWN2gpls2R0',
                'imgBanner' => 'https://boxofficevietnam.com/wp-content/uploads/2024/01/65672ba7d2a73642668289.jpeg',
            ],
            [
                'M_id' => 'F014',
                'tenPhim' => 'Captain America: Thế giới mới',
                'thoiLuong' => 120,
                'moTa' => 'Nhiệm vụ: Vén màn sự thật trước khi cả thế giới đổ máu. Captain America: Thế Giới Mới từ Marvel Studios ',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://media.lottecinemavn.com/Media/MovieFile/MovieImg/202501/11610_105_100001.jpg',
                'Trailer' => 'https://www.youtube.com/embed/45YkmSVLBrI',
                'imgBanner' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrR1k8C92vDCDfxbc1m-VgFY2tF90cxD2sXw&s',
            ],
            [
                'M_id' => 'F015',
                'tenPhim' => 'BUỔI HẸN HÒ KINH HOÀNG',
                'thoiLuong' => 95,
                'moTa' => 'Buổi hẹn hò đầu tiên sau nhiều năm của Violet nhanh chóng trở thành ác mộng khi cô nhận được những tin nhắn ẩn danh kỳ lạ. Kẻ gửi đe dọa giết con trai và em gái cô nếu cô không làm theo yêu cầu của hắn. Trong tuyệt vọng, Violet bị ép đến giới hạn cuối cùng: giết Henry, người đàn ông đang ngồi trước mặt cô. Đương nhiên, Violet không thể làm chuyện điên rồ đó. Cuối phim, cảnh sát đã xuất hiện để giải cứu Violet và Henry, đồng thời tống cổ kẻ nặc danh kia vào tù.',
                'trangThai' => 'Sắp chiếu',
                'Poster' => 'https://i.ytimg.com/vi/cQ1eYm_XIcA/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBf3KJ-Opqn-AVWEmzEdti-fhPWcg',
                'Trailer' => 'https://www.youtube.com/embed/cQ1eYm_XIcA',
                'imgBanner' => 'https://cdn.moveek.com/storage/media/cache/tall/679344e4e9aa3017021933.jpg',
            ],
            [
                'M_id' => 'F016',
                'tenPhim' => 'Đố Anh Còng Được Tôi ',
                'thoiLuong' => 95,
                'moTa' => 'Đố Anh Còng Được Tôi" (I, Executioner) là một trong những bộ phim chiếu rạp hành động Hàn Quốc hay kể về hành trình phá án đầy căng thẳng của thanh tra Seo Do Cheol (Hwang Jung Min) và đội điều tra trọng án. Họ đối mặt với một tên sát nhân thông minh, tàn nhẫn và chịu áp lực từ dư luận khi nhiều người ủng hộ hành động của hắn, thể hiện sự bất mãn với hệ thống tư pháp Hàn Quốc. Song song đó, Do Cheol còn phải đối diện với vấn đề gia đình khi con trai bị bắt nạt tại trường, trong khi đồng nghiệp Park Sun Woo (Jung Hae In) – một thanh tra trẻ tài năng – lại khiến anh nghi ngờ với những bí mật khó đoán.',
                'trangThai' => 'Đã chiếu',
                'Poster' => 'https://media.lottecinemavn.com/Media/MovieFile/MovieImg/202409/11560_105_100001.jpg',
                'Trailer' => 'https://www.youtube.com/embed/JgUWVooKSrA',
                'imgBanner' => 'https://www.elle.vn/wp-content/uploads/2024/08/29/605369/hwang-jung-min-trong-poster-do-anh-cong-duoc-toi.jpg',
            ],
            [
                'M_id' => 'F017',
                'tenPhim' => 'Hai muối',
                'thoiLuong' => 101,
                'moTa' => 'Muối – một cô gái mất mẹ từ khi vừa lọt lòng và lớn lên trong tình yêu thương của cha tại vùng đất xã đảo Thiềng Liềng. Bước ngoặt của hai cha con bắt đầu khi Muối trưởng thành, quyết định lên thành phố học tập và làm việc với ước mơ đổi đời để phụ giúp cha.',
                'trangThai' => 'Đã chiếu',
                'Poster' => 'https://2saigon.vn/wp-content/uploads/2024/08/HAI-MUOI-PAYOFF-POSTER-KTHUOC-FACEBOOK.jpg',
                'Trailer' => 'https://www.youtube.com/embed/MjxPoqCvvVs',
                'imgBanner' => 'https://2saigon.vn/wp-content/uploads/2024/08/HAI-MUOI-PAYOFF-POSTER-KTHUOC-FACEBOOK-.jpg',
            ],
            [
                'M_id' => 'F018',
                'tenPhim' => 'NÀNG BẠCH TUYẾT',
                'thoiLuong' => 108,
                'moTa' => 'Phiên bản chuyển thể người đóng của bộ phim hoạt hình Bạch Tuyết & Bảy chú lùn của Disney năm 1937.',
                'trangThai' => 'Sắp chiếu',
                'Poster' => 'https://i.ytimg.com/vi/cJh3IhW7wjo/maxresdefault.jpg',
                'Trailer' => 'https://www.youtube.com/embed/cJh3IhW7wjo',
                'imgBanner' => 'https://starlight.vn/Areas/Admin/Content/Fileuploads/images/Poster2024/snow-white.jpg',
            ],
            [
                'M_id' => 'F019',
                'tenPhim' => 'Cưới Ma: Hiến Mẹ Cho Quỷ ',
                'thoiLuong' => 104,
                'moTa' => 'Cưới ma: Hiến mẹ cho quỷ (Pengantin Iblis) là một bộ phim chiếu rạp kinh dị Indonesia của đạo diễn Azhar Kinoi Lubis, phim này được lấy cảm hứng từ nghi lễ cưới quỷ tại Indonesia, mang đến hàng loạt cảnh tượng rùng rợn, âm thanh ma quái. Ở bộ phim này, sẽ có tham gia diễn xuất của các diễn viên: Taskya Namya, Wafda Saifan Lubis, Arla Ailani, Givina Lukita, Bukie B. Mansyur,...',
                'trangThai' => 'Đang chiếu',
                'Poster' => 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/3/image/1800x/71252117777b696995f01934522c402d/6/4/640x396-cuoima.jpg',
                'Trailer' => 'https://www.youtube.com/embed/ZkW-Zb-EICA',
                'imgBanner' => 'https://i.ytimg.com/vi/Dg9YzHxEkWU/oardefault.jpg?sqp=-oaymwEiCJwEENAFSFqQAgHyq4qpAxEIARUAAAAAJQAAyEI9AICiQw==&rs=AOn4CLDEpn_Om4vWIs2AdRedj3AnPJMCHA',
            ],
            [
                'M_id' => 'F020',
                'tenPhim' => 'PHIM ĐIỆN ẢNH DORAEMON: NOBITA VÀ CUỘC PHIÊU LƯU VÀO THẾ GIỚI TRONG TRANH',
                'thoiLuong' => 140,
                'moTa' => 'Thông qua món bảo bối mới của Doraemon, cả nhóm bạn bước thế giới trong một bức tranh nổi tiếng và bắt gặp cô bạn bí ẩn tên Claire. Với lời mời của Claire, cả nhóm cùng đến thăm vương quốc Artoria, nơi ẩn giấu một viên ngọc quý mang tên Artoria Blue đang ngủ yên. Trên hành trình tìm kiếm viên ngọc, nhóm bạn Doraemon phát hiện một truyền thuyết về sự hủy diệt của thế giới, mà truyền thuyết đó dường như đang sống dậy! Liệu cả nhóm có thể phá hủy lời nguyền này và bảo vệ cả thế giới?',
                'trangThai' => 'Sắp chiếu',
                'Poster' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWzicdqpKvxTUoBMb0En_O6sM6L52Tlk6klw&s',
                'Trailer' => 'https://www.youtube.com/embed/Bz0zCdNBj1Q',
                'imgBanner' => 'https://cdn.galaxycine.vn/media/2025/3/11/doraemon-the-movie-nobitas-art-world-tales-2_1741663608345.jpg',
            ],
        ]);
    }
}
